### PR TITLE
fix: PASSWORD_RECOVERY event missing

### LINKED ISSUE #21: Password Recovery Does Not Update Auth Session
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Password Recovery flow does not work as expected for `@supabase/ssr` v0.4.0, whereas the same code works for v0.3.0. Confirmations, invitations, and magic links seem to work just fine, but password recovery does not. It does not update the session if the type is set to "recovery".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up SvelteKit SSR client as detailed [here](https://supabase.com/docs/guides/auth/server-side/sveltekit).
2. Create Forgot + Change Password pages as detailed [here](https://supabase.com/docs/guides/auth/passwords?queryGroups=flow&flow=pkce&queryGroups=framework&framework=sveltekit#resetting-a-password).
3. Update the Password Recovery email template to use the following template:
`{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=recovery&next=/change-password`
4. Ensure that the version of `@supabase/ssr` is v0.4.0
5. Attempt to reset password for a user through their email.
6. When the user visits the reset link, authentication fails.
7. Change the version of `@supabase/ssr` to v0.3.0
8. Try the password reset flow again.
9. It works.

## Expected behavior

The password recovery flow for v0.4.0 of `@supabase/ssr`, as detailed [here](https://supabase.com/docs/guides/auth/passwords?queryGroups=flow&flow=pkce&queryGroups=framework&framework=sveltekit#resetting-a-password), should authenticate the user and redirect them to the "/change-password" page.

## System information

- Supabase SSR: 0.4.0

## Additional context

I followed these guides:
https://supabase.com/docs/guides/auth/server-side/sveltekit
https://supabase.com/docs/guides/auth/passwords?queryGroups=flow&flow=pkce&queryGroups=framework&framework=sveltekit#resetting-a-password

A reference repo using v0.3.0 I used to confirm that the code worked, but updating it to v0.4.0 fails: https://github.com/j4w8n/sveltekit-supabase-ssr

### PR DESCRIPTION
**Pull request by j4w8n**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

When resetting a user's password with an email template which has a URL defining the `type` value of `recovery` and using `verifyOtp` in dev code to process the `token_hash` and `type`, the SSR server client's `onAuthStateChange` function does not recognize the `PASSWORD_RECOVERY` event that `verifyOtp` uses in this case. Therefore the new session does not get saved to storage and the user is not logged in, in order to reset their password.

## What is the new behavior?

User is logged in.

## Additional context

Fixes #21

### CODE REVIEW

**Comment by j4w8n** [comment]
I'm not sure what's going on with the `check-conventional-commits` check.

**Comment by J0** [comment]
Yeah I'm not sure - any chance you can rebase and push a commit with `feat:` or `fix`? Not sure if the merge commit I made is messing with the check

**Comment by J0** [comment]
Thanks for the PR btw :)

**Comment by j4w8n** [comment]
> Yeah I'm not sure - any chance you can rebase and push a commit with `feat:` or `fix`? Not sure if the merge commit I made is messing with the check

I'm sorry to say that I'm not familiar with that process. After a search, it seems you'd typically run the rebase command when on the branch, not `main`: `git rebase main`. But it gives me a merge conflict.

image
image

**Comment by J0** [comment]
@j4w8n if you could do that it would be perfect. Feel free to tag me there - will approve ASAP.

**Comment by j4w8n** [comment]
Closing. Will recreate.

**Pull request closed without merging**
