### PR TITLE
fix: check chunkedCookie is string in server client

### PR DESCRIPTION
**Pull request by pfftdammitchris**
Ensures chunked cookie checks are of the right type.

image

### CODE REVIEW

**Comment by J0** [comment]
Hey @pfftdammitchris 

Thanks for the PR! Could we trouble you to quickly run `npx prettier --write .` when free?

**Comment by pfftdammitchris** [comment]
Sure, here are the results:

image

**Comment by pfftdammitchris** [comment]
Sure

**Comment by pfftdammitchris** [comment]
> Hey @pfftdammitchris
> 
> Thanks for the PR! Could we trouble you to quickly run `npx prettier --write .` when free?

Yeah

**Comment by J0** [comment]
hmm I’ll try to file a PR against this so we can get it in

**Review by hf — APPROVED** [review]

**Comment by hf** [comment]
Hey @pfftdammitchris could you please fix the lint issues?

**Pull request closed without merging**
